### ISSUE TITLE
Kermits-126

### ISSUE THREAD

**Issue by Srjnnnn** [rloterh/MintSignupClone#2]
-To get the icon inside the input whether use a background property or you can use span next to the input element and give a negative margin to the span.
-Do not use one really long line for I forgot my user Id and better to put it to the next line.
-footer text-center is unnecessary and you could happy this class to the footer.
-Css 73 to 76, 107 to 109paddings are overused and re-assigned. It can be shortened.
-Using media queries is a good touch.
-All in all, it looks good.

**Comment by rloterh** [comment]
Resolved issues
